# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhkcRiULKJVTIs0jDqAMBh_IVmWIjYFR
"""

!pip install eurostat pandas

# process_eurostat.py

# === Imports ===
import eurostat
import pandas as pd
import os

# Make sure output folder exists
os.makedirs("data", exist_ok=True)

print("Libraries loaded, folder ready.")

# === Step 1: Fetch data ===

# Hospital discharges by diagnosis (Eurostat dataset)
df_raw = eurostat.get_data_df('hlth_co_disch2')

print("Raw shape:", df_raw.shape)
print(df_raw.head())

# === Step 2: Reshape to long format ===
df = df_raw.melt(
    id_vars=['freq', 'age', 'indic_he', 'unit', 'sex', 'icd10', 'geo\TIME_PERIOD'],
    var_name='time',
    value_name='value'
)

# Rename geo column
df = df.rename(columns={'geo\TIME_PERIOD': 'geo'})

print("Reshaped shape:", df.shape)
print(df.head())

# Drop rows with missing values
df = df.dropna(subset=['value']).copy()

# Convert year to int
df['time'] = df['time'].astype(int)

# Keep only records where age = TOTAL (all ages combined)
# and sex = T (total, both male and female combined).
# This simplifies the dataset so each row represents the full population,
# which is useful for high-level cross-country comparisons.
df = df[(df['age'] == 'TOTAL') & (df['sex'] == 'T')]

# Keep only hospital discharges unit if relevant
if 'unit' in df.columns:
    df = df[df['unit'] == 'P_HTHAB']   # adapt depending on meaning

# Filter to last 10 years (2012–2021)
df = df[df['time'] >= 2017]

print("Filtered shape:", df.shape)
print(df[['geo','icd10','time','value']].head(10))

# Save cleaned file
df.to_csv("data/hospital_discharges_clean.csv", index=False)

# Save latest year only
latest_year = df['time'].max()
df_latest = df[df['time'] == latest_year].copy()
df_latest.to_csv("data/hospital_discharges_latest.csv", index=False)

print(f"Saved processed files. Latest year = {latest_year}")